-d C:\GIT\TangNano_Stuff\TEst\impl\gwsynthesis\TEst.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst C:\GIT\TangNano_Stuff\TEst\src\TEst.cst
-cfg C:\GIT\TangNano_Stuff\TEst\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
